import Head from "next/head";
import { Inter } from "@next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }: any) {
  console.log(data);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="m-6">
        <h1 className={`${inter.className} text-3xl font-bold`}>Authors</h1>
        {data.authors.map((author: any, i: number) => (
          <Link key={i} href={`/authors/${author}`}>
            <p className="text-lg">{author}</p>
          </Link>
        ))}
      </main>
    </>
  );
}

export const getStaticProps = async () => {
  let response = await fetch("https://poetrydb.org/author", {
    method: "GET",
  });

  let data = await response.json();
  // console.log(data);

  return {
    props: {
      data,
    },
  };
};
